- name: Start vagrant
  hosts: localhost

  tasks:
  - name: Ensure VM is running
    vagrant_box:
      path:  /home/asilnikov/cm/ansible/day-3/Vagrantfile
      state: running
    register: vm

  - name: Update Inventory with newly created host
    add_host:
      name: node
      hostname: "{{ vm.Host }}"
      ansible_host: "{{ vm.HostName }}"
      ansible_port: "{{ vm.Port }}"
      ansible_connection: "ssh"
      ansible_user: "{{ vm.User }}"
      ansible_ssh_private_key_file: "{{ vm.IdentityFile }}"
      external_ip: "{{ vm.ip_adresses[1] }}"
    
  
  roles:
  - role: nginx        

- name: Provision Playground VM
  hosts: node

  vars:
    system_info: |-
        Distributive: "{{ ansible_distribution }}"
        Family:       "{{ ansible_distribution_file_variety }}"
        Version:      "{{ ansible_distribution_version }}"
  
  pre_tasks:
  - debug: msg={{ system_info.split('\n') }}

  roles:
  - role: java
  - role: tomcat
