---

 - name: enable and started tomcat
   systemd:
     name: tomcat.service
     enabled: yes
     state: started
     wait_for:
       timeout: 30
   notify:
     - systemd daemon reload

 - name: systemd daemon reload
   systemd: daemon_reload=yes
   become: yes
  
 - name: save tomcat details
   copy:
     content: |
       {
         "release": "{{ tomcat_version }}",
         "user": "{{ tomcat_user }}",
         "group": "{{ tomcat_group }}",
         "tomcat_home": "{{ tomcat_home }}",
         "catalina_home": "{{ tomcat_home }}/{{ tomcat_version }}",
         "tomcat_download_url": "{{ tomcat_url }}",
         "installed": "{{ ansible_date_time.iso8601 }}"
       }
     dest: /etc/ansible/facts.d/tomcat.fact
   become: yes

           
